import Head from 'next/head'
import { Contact, Intro, Navbar, Skills, Works } from '../components'
import { useContextState } from '../components/stateContext';
import { client } from '../lib/client'
import { BsArrowUp } from 'react-icons/bs';
import { useState } from 'react';

export default function Home({projects}) {
  const {dark} = useContextState();
  const [showTop, setShowTop] = useState(false);
  const goUp = ()=>{
    window.scroll(0,0);
    if(window.innerHeight >= "100vh"){
      setShowTop(true);
    }
  }

  return (
    <div className={dark ? "darkTheme":""}>
      <Head>
        <title>KGT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar/>
        <Intro/>
        <Skills/>
        <Contact/>
        <Works projects = {projects} />
      </main>

      <footer>
        <p>Copyright &copy;2022 KGT | All Rightes Reserverd.</p>
      </footer>
      {showTop && <div className='goUp' onClick={goUp}>
        <BsArrowUp className="icon"/>
      </div>}
    </div>
  )
}

export const getServerSideProps = async()=>{
  const query = '*[_type == "project"]';
  const projects = await client.fetch(query);

  return{
    props: {projects}
  }
}
